In [39]:
import cv2
import glob
import numpy as np

X_data = []
files = glob.glob ("C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal/*.JPG")
for myFile in files:
    print(myFile)
    image = cv2.imread (myFile)
    X_data.append (image)

X = np.array(X_data)
print('X_data shape:', np.array(X_data).shape)
print(X.shape)

C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00355.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00356.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00357.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00358.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00359.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00360.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00361.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00362.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00363.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00364.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00365.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00366.JPG
C:/Users/dbfgm/l

C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00482.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00483.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00484.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00485.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00486.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00487.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00488.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00489.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00490.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00491.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00492.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00493.JPG
C:/Users/dbfgm/l

C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00610.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00611.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00612.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00613.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00614.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00615.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00616.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00617.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00618.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00619.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00620.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/light-brown-coal\DSC00621.JPG
C:/Users/dbfgm/l

In [40]:
X

array([[[[143,  49,  20],
         [143,  50,  19],
         [144,  50,  15],
         ...,
         [233,  99,   0],
         [232, 101,   0],
         [234, 102,   1]],

        [[142,  48,  19],
         [141,  48,  17],
         [140,  48,  13],
         ...,
         [233, 100,   0],
         [231, 100,   0],
         [232, 101,   0]],

        [[141,  48,  17],
         [140,  47,  16],
         [139,  47,  12],
         ...,
         [236, 103,   0],
         [233, 102,   0],
         [232, 101,   0]],

        ...,

        [[100,  22,  16],
         [102,  24,  18],
         [104,  24,  17],
         ...,
         [170,  54,   0],
         [169,  53,   0],
         [169,  53,   0]],

        [[ 97,  20,  17],
         [101,  22,  19],
         [100,  22,  15],
         ...,
         [171,  55,   0],
         [169,  55,   2],
         [169,  55,   2]],

        [[ 97,  20,  17],
         [ 99,  22,  19],
         [101,  23,  17],
         ...,
         [170,  54,   1],
        

In [41]:
X.shape

(287, 480, 640, 3)

In [5]:
# X.transpose(0,3,1,2)

In [42]:
test_data = []
files = glob.glob ("C:/Users/dbfgm/light-brown-coal-classification/data/test/*.JPG")
for myFile in files:
    print(myFile)
    image = cv2.imread (myFile)
    test_data.append (image)

test = np.array(test_data)
print('test_data shape:', np.array(test_data).shape)
print(test.shape)

C:/Users/dbfgm/light-brown-coal-classification/data/test\18731_27310_4947.jpg
C:/Users/dbfgm/light-brown-coal-classification/data/test\DSC00349.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/test\DSC00350.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/test\DSC00351.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/test\DSC00352.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/test\DSC00353.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/test\DSC00354.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/test\DSC00642.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/test\DSC00643.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/test\DSC00644.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/test\DSC00645.JPG
C:/Users/dbfgm/light-brown-coal-classification/data/test\DSC00646.JPG
test_data shape: (12, 480, 640, 3)
(12, 480, 640, 3)


In [43]:
from keras.applications.resnet50 import ResNet50

image_h = 480
image_w = 640
def extract_resnet(X):  
    # X : images numpy array
    resnet_model = ResNet50(input_shape=(image_h, image_w, 3), weights='imagenet', include_top=False)  
# Since top layer is the fc layer used for predictions
    features_array = resnet_model.predict(X)
    return features_array

In [44]:
X_train = extract_resnet(X)

In [45]:
X_train

array([[[[1.9339156e-01, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
         [7.9366386e-01, 6.4026523e-01, 0.0000000e+00, ...,
          0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
         [1.9707580e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
         ...,
         [5.2234650e-02, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
         [1.0271528e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
         [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 0.0000000e+00, 0.0000000e+00]],

        [[2.2028127e+00, 0.0000000e+00, 0.0000000e+00, ...,
          1.3042483e+00, 0.0000000e+00, 0.0000000e+00],
         [4.6147442e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
         [3.4723985e+00, 0.0000000e+00, 0.0000000e+00, .

In [46]:
X_train.shape

(287, 15, 20, 2048)

In [47]:
X_test = extract_resnet(test)

In [48]:
X_test.shape

(12, 15, 20, 2048)

In [49]:
import numpy as np

def im2col(input_data, filter_h, filter_w, stride=1, pad=0):
    """
    다수의 이미지를 입력받아 2차원 배열로 변환한다(평탄화).

    Parameters
    ----------
    input_data : 4차원 배열 형태의 입력 데이터(이미지 수, 채널 수, 높이, 너비)
    filter_h : 필터의 높이
    filter_w : 필터의 너비
    stride : 스트라이드
    pad : 패딩

    Returns
    -------
    col : 2차원 배열
    """
    N, C, H, W = input_data.shape
    out_h = (H + 2 * pad - filter_h) // stride + 1
    out_w = (W + 2 * pad - filter_w) // stride + 1

    img = np.pad(input_data, [(0, 0), (0, 0), (pad, pad), (pad, pad)], 'constant')
    col = np.zeros((N, C, filter_h, filter_w, out_h, out_w))

    for y in range(filter_h):
        y_max = y + stride * out_h
        for x in range(filter_w):
            x_max = x + stride * out_w
            col[:, :, y, x, :, :] = img[:, :, y:y_max:stride, x:x_max:stride]

    col = col.transpose(0, 4, 5, 1, 2, 3).reshape(N * out_h * out_w, -1)
    return col

In [50]:
X_train.shape

(287, 15, 20, 2048)

In [60]:
step_1 = im2col(X,2,2,2,0) # 입력 데이터(x)를 필터크기(2x2)와 stride(2), padding(0)으로 평탄화함
step_1

array([[143.,  49., 143., ...,  20.,  99.,  22.],
       [144.,  50., 143., ...,  23., 102.,  21.],
       [144.,  51., 148., ...,  25., 107.,  24.],
       ...,
       [149.,  52., 148., ...,  90., 192.,  88.],
       [146.,  49., 145., ...,  89., 191.,  87.],
       [147.,  47., 149., ...,  86., 188.,  84.]])

In [61]:
step_1.shape

(91840, 1920)

In [62]:
X_train = step_1

In [63]:
step_2 = im2col(test,2,2,2,0) # 입력 데이터(x)를 필터크기(2x2)와 stride(2), padding(0)으로 평탄화함
step_2

array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       ...,
       [136.,  51., 134., ...,  63., 162.,  64.],
       [132.,  46., 131., ...,  65., 163.,  65.],
       [130.,  45., 130., ...,  65., 158.,  63.]])

In [64]:
X_test = step_2

In [65]:
X_test.shape

(3840, 1920)

In [16]:
###############################

In [66]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest
from sklearn import svm

# Apply standard scaler to output from resnet50
ss = StandardScaler()
ss.fit(X_train)
X_train = ss.transform(X_train)
X_test = ss.transform(X_test)

# Take PCA to reduce feature space dimensionality
pca = PCA(n_components=512, whiten=True)
pca = pca.fit(X_train)
print('Explained variance percentage = %0.2f' % sum(pca.explained_variance_ratio_))
X_train = pca.transform(X_train)
X_test = pca.transform(X_test)

# Train classifier and obtain predictions for OC-SVM
oc_svm_clf = svm.OneClassSVM(gamma=0.001, kernel='rbf', nu=0.08)  # Obtained using grid search
if_clf = IsolationForest(contamination=0.08, max_features=1.0, max_samples=1.0, n_estimators=40)  # Obtained using grid search

oc_svm_clf.fit(X_train)
if_clf.fit(X_train)

oc_svm_preds = oc_svm_clf.predict(X_test)
if_preds = if_clf.predict(X_test)

Explained variance percentage = 0.99


In [67]:
oc_svm_preds

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [68]:
if_preds

array([1, 1, 1, ..., 1, 1, 1])